# Generated by Django 5.0.4 on 2025-06-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dui',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
