# Generated by Django 5.0.4 on 2025-06-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0002_crear_roles_iniciales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografiasvehiculo',
            name='url_fotografia',
            field=models.ImageField(upload_to='vehiculos/'),
        ),
    ]
