# Generated by Django 5.0.4 on 2025-06-23 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_alter_fotografiasvehiculo_id_vehiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientos',
            name='id_vehiculo',
            field=models.ForeignKey(blank=True, db_column='id_vehiculo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.vehiculos'),
        ),
    ]
