# Generated by Django 5.0.4 on 2025-06-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_alter_fotografiasvehiculo_url_fotografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculos',
            name='tipo_placa',
            field=models.CharField(choices=[('P', 'Vehículo particular'), ('A', 'Vehículo de alquiler'), ('AB', 'Autobús'), ('C', 'Vehículo de carga'), ('M', 'Motocicleta particular'), ('H', 'Vehículo del Estado'), ('N', 'Vehículo de instituciones autónomas'), ('O', 'Organismo internacional'), ('CD', 'Cuerpo diplomático'), ('CC', 'Cuerpo consular'), ('MI', 'Misión internacional'), ('U', 'Uso municipal'), ('E', 'Vehículo escolar'), ('T', 'Transporte público (colectivo)'), ('TC', 'Transporte de carga comercial'), ('R', 'Remolque'), ('TR', 'Tractor o maquinaria agrícola/industrial'), ('F', 'Fuerza Armada'), ('D', 'Vehículo en demostración (agencia/concesionario)'), ('Z', 'Vehículo de zona franca o especial'), ('B', 'Mototaxi / Tricimoto / Bicimoto'), ('V', 'Vehículo temporal o de visitante'), ('POL', 'POLIZA (Placa provisional)')], default='P', max_length=4),
        ),
    ]
