# Generated by Django 5.0.4 on 2025-06-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_vehiculos_tipo_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dui',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
