# Generated by Django 5.1.5 on 2025-06-13 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_vehiculos_tipo_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientorepuestos',
            name='id_repuesto',
            field=models.ForeignKey(db_column='id_repuesto', on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.repuestos'),
        ),
    ]
