# Generated by Django 5.1.5 on 2025-06-13 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_alter_mantenimientorepuestos_id_repuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientorepuestos',
            name='id_mantenimiento',
            field=models.ForeignKey(db_column='id_mantenimiento', on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.mantenimientos'),
        ),
    ]
