# Generated by Django 5.0.4 on 2025-06-13 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_alter_usuarios_dui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dui',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
