# Generated by Django 5.0.4 on 2025-06-13 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0006_alter_usuarios_dui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='dui',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
