# Generated by Django 5.0.4 on 2025-06-13 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0007_alter_usuarios_dui'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculos',
            name='id_usuario_propietario',
            field=models.ForeignKey(db_column='id_usuario_propietario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
