# Generated by Django 5.0.4 on 2025-06-13 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0008_alter_vehiculos_id_usuario_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografiasvehiculo',
            name='id_vehiculo',
            field=models.ForeignKey(db_column='id_vehiculo', on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.vehiculos'),
        ),
    ]
